version: "3.3"
services:
  lttng_filebench:
    build: .
    tty: true
    volumes:
      - /lib/modules:/lib/modules
      - /usr/src:/usr/src
      - /sys/kernel/debug/:/sys/kernel/debug/
      - /tmp/lttng-traces/:/tmp/lttng-traces/
      - ./fileserver.f:/filebench/workloads/fileserver.f
    cap_add:
      - ALL
    privileged: true
    network_mode: host
    pid: host
    environment:
      - LTTNG_SESSION_NAME=sample-session
      - LTTNG_SYSCALLS=read;write;open;close;stat;fstat;lstat;lseek;pread64;pwrite64;readv;writev;socket;connect;accept;sendto;recvfrom;sendmsg;recvmsg;bind;listen;socketpair;setsockopt;getsockopt;fsync;fdatasync;truncate;ftruncate;rename;creat;unlink;readlink;mknod;fstatfs;readahead;setxattr;lsetxattr;fsetxattr;getxattr;lgetxattr;fgetxattr;listxattr;llistxattr;flistxattr;removexattr;lremovexattr;fremovexattr;openat;mknodat;newfstatat;unlinkat;renameat;readlinkat;accept4;renameat2
      - LTTNG_TRACEPOINTS=sched_process_fork
      - LTTNG_EXTRA_CONTEXT=pid;tid;hostname;procname;ppid
      - LTTNG_LIVE=True
      - LTTNG_DEFAULT=False
      - POST_TRACE_ANALYSIS=False

  babeltrace:
    image: pedrordgs/babeltrace:latest
    tty: true
    network_mode: host
    volumes:
      - /tmp/lttng-traces/:/tmp/lttng-traces/
    environment:
      - LTTNG_ADDRESS=127.0.0.1
      - ES_ADDRESSES=http://127.0.0.1:31111
      - ES_USER=dio
      - ES_PWD=diopw
      - ES_INDEX_NAME=dio_trace
      - ELK_ENABLED=False
      - BABELTRACE_DUMMY=False
      - LTTNG_LIVE=True
      - BABELTRACE_DISCARD=False